cloud_provider: 'azure'
source_file_url: 'https://pocairflow.blob.core.windows.net/poc2/demo/demo.csv'
source_file_path: 'demo/demo.csv'
destination_file_path: 'demo/demo.csv'
source_bucket_name: 'poc2'
destination_bucket_name: 'temp'
file_name: 'demo/demo.csv'
local_file_path: '/opt/airflow/dags/repo/POC-AIRFLOW_v2/project/cloud/demo.csv'
#local_file_path: 'usr/local/airflow/custom/payload1.json'
function_name:
sheet_name:
upload_file_name: 'demo/demo.csv'
upload_to_bucket_name: 'poc2'
csv_metadata_blob_name: 'csv_metadata.json'
