cloud_provider: 'azure'
source_file_url: 'https://pocairflow.blob.core.windows.net/poc2/demo/payload1.json'
source_file_path: 'demo/payload1.json'
destination_file_path: 'demo/payload1.json'
source_bucket_name: 'poc2'
destination_bucket_name: 'temp'
file_name: 'demo/payload1.json'
local_file_path: '/opt/airflow/dags/repo/POC-AIRFLOW_v2/project/custom/payload1.json'
#local_file_path: 'usr/local/airflow/custom/payload1.json'
function_name:
sheet_name:
upload_file_name: 'demo/payload1.json'
upload_to_bucket_name: 'poc2'
