cloud_provider: 'azure'
source_file_url: 'https://pocairflow.blob.core.windows.net/poc2/'
#source_file_path: 'demo/'
#destination_file_path: 'demo/'
source_bucket_name: 'poc2'
destination_bucket_name: 'temp'
#file_name: 'demo/demo.csv'
#local_file_path: 'C:/Users/vaishnavi.ruikar/PycharmProjects/POC-AIRFLOW/project/custom/files/'
local_file_path: '/opt/airflow/dags/repo/POC-AIRFLOW_v3/project/custom/files/'
function_name:
sheet_name:
upload_file_path: 'demo/'
upload_to_bucket_name: 'poc2'
csv_metadata_blob_name: 'loan_csv_metadata.json'
mongo_database_name: 'dbpocdom'
mongo_collection: 'sales_unshard'
