cloud_provider: 'azure'
source_file_url: 'https://pocairflow.blob.core.windows.net/poc/demo/input.json'
source_file_path: 'demo/input.json'
destination_file_path: 'demo/input.json'
source_bucket_name: 'poc'
destination_bucket_name: 'temp'
file_name: 'input.json'
local_file_path: 'demo.csv'
function_name:
sheet_name:
